function validateForm() {
    if(document.getElementById("tiene_licencia_conducir_no").checked) {
        document.getElementById("licencia").setAttribute("disabled", true);
    }else{
        document.getElementById("licencia").removeAttribute("disabled");
    }
    if(document.getElementById('como_supo_a').checked){
        document.getElementById('como_supo_otro').setAttribute('disabled',true);
    }else{
        document.getElementById('como_supo_otro').removeAttribute('disabled');
    }
    if(document.getElementById('parientes_trabajando_no').checked){
        document.getElementById('nom_parientes_trabajando').setAttribute('disabled',true);
    }else{
        document.getElementById('nom_parientes_trabajando').removeAttribute('disabled');
    }
    if(document.getElementById('otros_ingresos_no').checked){
        document.getElementById('desc_ingresos').setAttribute('disabled',true);
        document.getElementById('importe_mensual').setAttribute('disabled',true);
    }else{
        document.getElementById('desc_ingresos').removeAttribute('disabled');
        document.getElementById('importe_mensual').removeAttribute('disabled');
    }
    if(document.getElementById('trabaja_conyuge_no').checked){
        document.getElementById('donde_conyuge').setAttribute('disabled',true);
        document.getElementById('importe_mensual_conyuge').setAttribute('disabled',true);
    }else{
        document.getElementById('donde_conyuge').removeAttribute('disabled');
        document.getElementById('importe_mensual_conyuge').removeAttribute('disabled');
    }
    if(document.getElementById('afianzado_no').checked){
        document.getElementById('nom_afianzado').setAttribute('disabled',true);
    }else{
        document.getElementById('nom_afianzado').removeAttribute('disabled');
    }
    if(document.getElementById('casa_propia_no').checked){
        document.getElementById('valor_aprox').setAttribute('disabled',true);
    }else{
        document.getElementById('valor_aprox').removeAttribute('disabled');
    }
    if(document.getElementById('afiliado_no').checked){
        document.getElementById('nom_afiliado').setAttribute('disabled',true);
    }else{
        document.getElementById('nom_afiliado').removeAttribute('disabled');
    }
    if(document.getElementById('renta_no').checked){
        document.getElementById('renta_mensual').setAttribute('disabled',true);
    }else{
        document.getElementById('renta_mensual').removeAttribute('disabled');
    }
    if(document.getElementById('seguro_no').checked){
        document.getElementById('nom_seguro').setAttribute('disabled',true);
    }else{
        document.getElementById('nom_seguro').removeAttribute('disabled');
    }
    if(document.getElementById('auto_propia_no').checked){
        document.getElementById('marca').setAttribute('disabled',true);
        document.getElementById('modelo').setAttribute('disabled',true);
    }else{
        document.getElementById('marca').removeAttribute('disabled');
        document.getElementById('modelo').removeAttribute('disabled');
    }
    if(document.getElementById('viajar_si').checked){
        document.getElementById('razon_viajar').setAttribute('disabled',true);
    }else{
        document.getElementById('razon_viajar').removeAttribute('disabled');
    }
    if(document.getElementById('deudas_no').checked){
        document.getElementById('who_deuda').setAttribute('disabled',true);
        document.getElementById('importe_deuda').setAttribute('disabled',true);
        document.getElementById('abono_mensual').setAttribute('disabled',true);
    }else{
        document.getElementById('who_deuda').removeAttribute('disabled');
        document.getElementById('importe_deuda').removeAttribute('disabled');
        document.getElementById('abono_mensual').removeAttribute('disabled');
    }
    if(document.getElementById('residencia_si').checked){
        document.getElementById('razon_residencia').setAttribute('disabled',true);
    }else{
        document.getElementById('razon_residencia').removeAttribute('disabled');
    }
}